# Generated by Django 5.1.4 on 2025-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_factura_metodo_pago_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_recibido',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
