# Generated by Django 5.1.4 on 2025-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_factura_cambio_alter_factura_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
