# Generated by Django 5.1.4 on 2025-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_impuesto_porcentaje_alter_itemfactura_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cambio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_recibido',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='recargo_tarjeta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_descuento',
            field=models.FloatField(),
        ),
    ]
