# Generated by Django 5.1.4 on 2025-02-02 17:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_factura_cambio_alter_factura_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('facturas', models.ManyToManyField(related_name='historiales', through='facturacion.FacturaHistorial', to='facturacion.factura')),
            ],
        ),
        migrations.AddField(
            model_name='facturahistorial',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.historialfactura'),
        ),
        migrations.DeleteModel(
            name='HistorialDeFactura',
        ),
    ]
