# Generated by Django 5.1.4 on 2025-02-02 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_itemfactura_options_alter_promocion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='facturacion.factura'),
        ),
    ]
