# Generated by Django 5.1.5 on 2025-02-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
    ]
