# Generated by Django 5.1.4 on 2025-02-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0005_remove_personal_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name_plural': 'Personal'},
        ),
    ]
