# Generated by Django 5.1.5 on 2025-02-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0006_alter_personal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_reserva_finalizada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario_inicio',
        ),
    ]
