# Generated by Django 5.1.4 on 2025-02-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0007_remove_persona_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='cantidad_uso',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='hora_disponible',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='mesas_unidas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_personas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='identificador',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero_asientos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mesas.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mesas.mesa'),
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
