# Generated by Django 5.1.5 on 2025-02-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('mesas', '0003_alter_reserva_cliente'),
        ('pedidos', '0003_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='nombre_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesas.cliente', verbose_name='Nombre del Cliente'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
