# Generated by Django 5.1.5 on 2025-02-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_remove_mesa_identificador_mesa_cantidad_uso_and_more'),
        ('pedidos', '0006_alter_pedido_mesa_delete_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.cliente', verbose_name='Cliente'),
        ),
    ]
