# Generated by Django 5.1.5 on 2025-02-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('menu', '0002_producto_cantidad_vendida'),
        ('mesas', '0004_remove_mesa_identificador_mesa_cantidad_uso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mesas.persona')),
                ('pedidosAtendidos', models.IntegerField(default=0)),
            ],
            bases=('mesas.persona',),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.cliente'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='impuestos',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='facturacion.ItemPedido', to='menu.producto'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
