# Generated by Django 5.1.5 on 2025-02-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_pedido_productos_remove_pedido_cliente_and_more'),
        ('mesas', '0004_remove_mesa_identificador_mesa_cantidad_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesas.mesa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='mesero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.mesero'),
        ),
    ]
