# Generated by Django 5.1.4 on 2025-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_mesa_factura_mesero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago_efectivo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago_tarjeta',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago_transferencia',
        ),
        migrations.AddField(
            model_name='factura',
            name='cambio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_recibido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='factura',
            name='recargo_tarjeta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='factura',
            name='referencia_transferencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PagoEfectivo',
        ),
        migrations.DeleteModel(
            name='PagoTarjeta',
        ),
        migrations.DeleteModel(
            name='PagoTransferencia',
        ),
    ]
