# Generated by Django 5.1.4 on 2025-02-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_facturahistorial_historialfactura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialfactura',
            name='facturas',
        ),
        migrations.DeleteModel(
            name='FacturaHistorial',
        ),
    ]
