# Generated by Django 5.1.4 on 2025-02-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_remove_historialfactura_facturas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfactura',
            options={'verbose_name_plural': 'Items de Factura'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name_plural': 'Promociones'},
        ),
    ]
