# Generated by Django 5.1.4 on 2025-02-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventarioprincipal_remove_categoria_menu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaInventario',
        ),
        migrations.RemoveField(
            model_name='reporteconsumo',
            name='cantidad_consumida',
        ),
    ]
