# Generated by Django 5.1.4 on 2025-02-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_categoria_categoriainventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
