# Generated by Django 5.1.4 on 2025-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_insumo_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
