# Generated by Django 5.1.5 on 2025-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendida',
            field=models.IntegerField(default=0),
        ),
    ]
