# Generated by Django 5.1.5 on 2025-02-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_remove_cliente_activo'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='nombre_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='mesas.cliente', verbose_name='Nombre del Cliente'),
        ),
    ]
