# Generated by Django 5.1.5 on 2025-02-01 21:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_producto_cantidad_vendida'),
        ('mesas', '0004_remove_mesa_identificador_mesa_cantidad_uso_and_more'),
        ('pedidos', '0008_pedido_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='reserva',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesas.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('ENPROCESO', 'En Proceso')], default='PENDIENTE', max_length=50),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedidos.ItemPedido', to='menu.producto'),
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
