# Generated by Django 5.1.4 on 2025-02-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_categoria_categoriainventario_and_more'),
        ('menu', '0002_producto_cantidad_vendida'),
        ('pedidos', '0009_remove_pedido_actualizado_en_remove_pedido_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='menu.producto')),
            ],
        ),
    ]
