# Generated by Django 5.1.4 on 2025-02-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimientoinventario_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriainventario',
            options={'verbose_name_plural': 'Categorias de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='inventarioprincipal',
            options={'verbose_name_plural': 'Inventarios Principales'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='reporteconsumo',
            options={'verbose_name_plural': 'Reportes de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='reporteinventario',
            options={'verbose_name_plural': 'Reportes de Inventario'},
        ),
    ]
